name: Webpage Build

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: folder make
      run: |
           mkdir -p folder && cp ab.txt folder
           cd folder && ls
           
    - name: upload to s3
      uses: shallwefootball/s3-upload-action@master
      with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: folder
          destination_dir: github/
